### ISSUE TITLE
My suggestion in your project 

### ISSUE THREAD

**Issue by Syafiq1331** [diosamuel/zippydamn-lib#1]
Blocked porn videos or etc from zippyshare to zippydamn

**Comment by diosamuel** [comment]
> Blocked porn videos or etc from zippyshare to zippydamn

Hello, this is just library for extract [Zippyshare](https://zippyshare.com) url to a **downloadable** url
and for searching file in zippyshare hosting

So, in order to block porn or unpleasant file, big sorry, i think "impossible" to do that.
We can't detect porn link by title or etc

And as i say, this is just library for extract & search file, so I'm not responsible for the link she/he inputs

Dont worry, im waiting for another issue & PR 💪, Happy hacktoberfest!
